---
title: "Final Project"
author: "Jacob Hansen"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)

# Loading in the relevant libraries as needed.

library(tidyverse)
library(readxl)
library(readr)
library(readr)
library(janitor)
library(ggplot2)
library(ggthemes)
library(tidycensus)
census_api_key("bc6535753047a343a531d92be52cfa8b40d17182", install = TRUE, overwrite=TRUE)
readRenviron("~/.Renviron")
library(stringr)
library(gganimate)
library(gt)
library(plotly)
library(broom)
```

```{r reg_data_cleaning, include=FALSE}

# Here, I do most of my data cleaning. Each of these files, which come from the
# Arizona Secretary of State's Office, were slightly different in format, so I
# decided to do them all individually. They were then joined together and
# cleaned, to later be added to the singular dataset used for most of the
# project.

# I knew from the beginning of the project I wanted to limit my observations to
# Democrats and Republicans, so I only selected for those columns.

# This project also helped me get really comfortable with pivot_longer() and
# pivot_wider()!

reg_2004 <- read.csv("raw-data/2005-01-01.csv", skip = 5) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2004") %>% 
  head(15) %>% 
  mutate(year = 2004) %>% 
  select(county, year, democratic, republican, total)

reg_2006 <- read.csv("raw-data/2007-01-01.csv", skip = 4) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2006") %>% 
  head(15) %>% 
  mutate(year = 2006) %>% 
  select(county, year, democratic, republican, total)

reg_2008 <- read.csv("raw-data/2009-01-01.csv", skip = 4) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2008") %>% 
  head(15) %>% 
  mutate(year = 2008) %>% 
  select(county, year, democratic, republican, total)

reg_2010 <- read.csv("raw-data/2011-01-01.csv", skip = 4) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2010") %>% 
  head(15) %>% 
  mutate(year = 2010) %>% 
  select(county, year, democratic, republican, total)

reg_2012 <- read.csv("raw-data/2013-01-01.csv", skip = 4) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2012") %>% 
  head(15) %>% 
  mutate(year = 2012) %>% 
  select(county, year, democratic, republican, total)

reg_2014 <- read.csv("raw-data/2015-01-01.csv", skip = 4) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2014") %>% 
  head(15) %>% 
  mutate(year = 2014) %>% 
  select(county, year, democratic, republican, total)

reg_2016 <- read.csv("raw-data/2017-01-01.csv", skip = 4) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2016") %>% 
  head(15) %>% 
  mutate(year = 2016) %>% 
  select(county, year, democratic, republican, total)

reg_2018 <- read.csv("raw-data/2019-01-01.csv", skip = 5) %>% 
  clean_names() %>% 
  filter(date_period == "G.E. 2018") %>% 
  head(15) %>% 
  mutate(year = 2018) %>% 
  select(county, year, democratic, republican, total)

reg_2004_to_2018 <- reg_2004 %>% 
  full_join(reg_2006) %>% 
  full_join(reg_2008) %>% 
  full_join(reg_2010) %>% 
  full_join(reg_2012) %>%
  full_join(reg_2014) %>%
  full_join(reg_2016) %>%
  full_join(reg_2018) %>%
  arrange(county) %>% 
  pivot_longer(names_to = "party_old",
               values_to = "registration",
               cols = c(democratic:republican)) %>% 
  mutate(party = ifelse(party_old == "democratic", "democrat", "republican")) %>% 
  select(county, year, party, registration, total) %>% 
  mutate(percentage = (registration / total) * 100)
```

```{r vote_data_cleaning, include=FALSE}

# Here I had to load in some of the data from the MIT election labs. I'm not
# sure why, but I had a lot of trouble remaining this Rdata file, which always
# seemed to load in as "x". Thankfully there wasn't any other dataset named x to
# be confused with, so it ended up being okay.

# I decided to simplify the research be focusing only on "top-ballot" candidates
# for the two major parties. Essentially, this meant that in Presidential
# election years I focused on presidential election results, in Senate election
# years I focused on Senate election results, and in years without presidential
# or Senate elections, I used gubernatorial races. This eliminated the need to
# consider "split ballots." Also, top-ballot races always receive the most votes
# (before voters get bored and give up with more niche races). For these
# reasons, this seemed like a good analytical choice.

load("raw-data/countypres_2000-2016.Rdata")

AZ_pres <- x %>% 
  filter(state == "Arizona") %>% 
  select(year, county, office, candidate, party, candidatevotes, totalvotes) %>% 
  mutate(percentage = (candidatevotes / totalvotes) * 100) %>% 
  filter(party == "democrat" | party == "republican")

AZtopballot <- read.csv("raw-data/azcountytopballot_2006-2018.csv") %>% 
  clean_names() %>% 
  mutate(percentage = (candidatevotes / totalvotes) * 100)

AZ_elections_2004_2018 <- AZ_pres %>% 
  full_join(AZtopballot, by = c("year" = "i_year", "county", "office", "candidate", "party", "candidatevotes", "totalvotes", "percentage")) %>% 
  arrange(year) %>% 
  filter(year > 2002)
```

```{r race_data, echo=FALSE}

# Like the data from the AZ secretary of state, the census data was a real pain
# to work with because each year--I focused on even years to match the elections
# I was analyzing--was done slightly differently. I also had to rename all of
# the variable names, which were coded. There was also often a single line of
# data that messed up my cleaning that I could not remove in R, so I deleted the
# line (which was inconsequential) from the csv file (not best practices, I'm
# sure! still lots to learn with data cleaning).

# I then was able to join all of these years' worth of data together into one
# dataset.

race2010 <- read_csv("raw-data/ACSDP5Y2010.DP05_data_with_overlays_2020-04-24T142342.csv",
                     col_types = cols("dp05_0066e" = col_double(),
                                      "dp05_0066pe" = col_double(),
                                      "dp05_0001e" = col_double())) %>% 
  clean_names() %>% 
  mutate(year = 2010) %>% 
  filter(name != "Arizona") %>% 
  mutate(county = word(name, start = 1L, end = -3, sep = fixed(" "))) %>%
  mutate(hisp_pop = dp05_0066e) %>% 
  mutate(hisp_perc = dp05_0066pe) %>%
  mutate(total_pop = dp05_0001e) %>% 
  select(county, year, hisp_pop, hisp_perc, total_pop)

race2012 <- read_csv("raw-data/ACSDP5Y2012.DP05_data_with_overlays_2020-04-24T141301.csv",
                     col_types = cols("dp05_0066e" = col_double(),
                                      "dp05_0066pe" = col_double(),
                                      "dp05_0001e" = col_double())) %>% 
  clean_names() %>% 
  mutate(year = 2012) %>% 
  filter(name != "Arizona") %>% 
  mutate(county = word(name, start = 1L, end = -3, sep = fixed(" "))) %>%
  mutate(hisp_pop = dp05_0066e) %>% 
  mutate(hisp_perc = dp05_0066pe) %>%
  mutate(total_pop = dp05_0001e) %>% 
  select(county, year, hisp_pop, hisp_perc, total_pop)

race2014 <- read_csv("raw-data/ACSDP5Y2014.DP05_data_with_overlays_2020-04-24T140611.csv",
                     col_types = cols("dp05_0066e" = col_double(),
                                      "dp05_0066pe" = col_double(),
                                      "dp05_0001e" = col_double())) %>% 
  clean_names() %>% 
  mutate(year = 2014) %>% 
  mutate(county = word(name, start = 1L, end = -3, sep = fixed(" "))) %>%
  mutate(hisp_pop = dp05_0066e) %>% 
  mutate(hisp_perc = dp05_0066pe) %>%
  mutate(total_pop = dp05_0001e) %>% 
  select(county, year, hisp_pop, hisp_perc, total_pop)

race2016 <- read_csv("raw-data/ACSDP5Y2016.DP05_data_with_overlays_2020-04-24T125340.csv",
                     col_types = cols("dp05_0066e" = col_double(),
                                      "dp05_0066pe" = col_double(),
                                      "dp05_0001e" = col_double())) %>% 
  clean_names() %>% 
  mutate(year = 2016) %>% 
  mutate(county = word(name, start = 1L, end = -3, sep = fixed(" "))) %>%
  mutate(hisp_pop = dp05_0066e) %>% 
  mutate(hisp_perc = dp05_0066pe) %>%
  mutate(total_pop = dp05_0001e) %>% 
  select(county, year, hisp_pop, hisp_perc, total_pop)

race2018 <- read_csv("raw-data/ACSDP5Y2018.DP05_data_with_overlays_2020-04-24T123622.csv",
                     col_types = cols("dp05_0071e" = col_double(),
                                      "dp05_0071pe" = col_double(),
                                      "dp05_0001e" = col_double())) %>% 
  clean_names() %>% 
  mutate(year = 2018) %>% 
  mutate(county = word(name, start = 1L, end = -3, sep = fixed(" "))) %>%
  mutate(hisp_pop = dp05_0071e) %>% 
  mutate(hisp_perc = dp05_0071pe) %>% 
  mutate(total_pop = dp05_0001e) %>%
  select(county, year, hisp_pop, hisp_perc, total_pop)

race <- race2010 %>%
  full_join(race2012, by = c("county", "year", "hisp_pop", "hisp_perc", "total_pop")) %>% 
  full_join(race2014, by = c("county", "year", "hisp_pop", "hisp_perc", "total_pop")) %>% 
  full_join(race2016, by = c("county", "year", "hisp_pop", "hisp_perc", "total_pop")) %>% 
  full_join(race2018, by = c("county", "year", "hisp_pop", "hisp_perc", "total_pop")) %>% 
  arrange(county)
```

```{r combining_data, echo=FALSE}

# I knew I wanted to be able to just analyze one complete dataset, so I combined
# all of the above data into one tibble, "data". I then saved this file as an
# rds so that I didn't have to copy all of the data cleaning in the shiny app.R
# file.

# The few modifications I needed to make to the data for various graphs in the
# shiny app are included at the top of the shiny file.

data <- race %>% 
  left_join(AZ_elections_2004_2018, by = c("year", "county")) %>% 
  left_join(reg_2004_to_2018, by = c("year", "county", "party"),
            suffix = c("_votes", "_reg"))

saveRDS(data, file = "data_4-24.rds")

# I originally was using functions to make different plots, with the input being
# the county name. I did this before I really knew how shiny worked. Once I was
# putting together the app, I realized shiny already had input-based
# functionality enabled. For this reason, just the internal code of the
# functions--which creates a ggplot--were included in the shiny app. But I have
# left the reg_plot and the vote_plot functions in here to show my initial
# approach to creating these graphs dynamically.

reg_plot <- function(x){
  data %>% 
    filter(county == x) %>% 
    ggplot(aes(x = year, y = percentage_reg, color = party)) +
    geom_line(show.legend = FALSE, size = 0.54) +
    scale_color_manual(values = c("blue", "red")) +
    labs(x = "Year",
         y = "Registration",
         title = "Party Registration Percentages",
         subtitle = "Selected County in Arizona",
         caption = "Sources: MIT Election Data + Science Lab,
                    Arizona Secretary of State,
                    U.S. Census Bureau") +
    theme_fivethirtyeight() +
    scale_x_continuous(breaks = seq(2010, 2018, by = 2))
}

vote_plot <- function(x){
  data %>% 
  filter(county == x) %>% 
  group_by(party) %>% 
  ggplot(aes(x = year, y = percentage_votes, color = party)) +
    geom_line(show.legend = FALSE, size = 0.54) +
    theme_hc() +
    scale_color_manual(values = c("blue", "red")) +
    scale_x_continuous(breaks = seq(2010, 2018, by = 2)) +
    labs(x = "Year",
         y = "Votes",
         title = "Vote Percentage for Top-Ballot Candidates",
         subtitle = "Selected County in Arizona",
         caption = "Sources: MIT Election Data + Science Lab,
                    Arizona Secretary of State,
                    U.S. Census Bureau")
}

vote_plot("Pima")
```

```{r hisp_pop_statewide, include = FALSE}

# We now get into the point where I composed the code for creating graphs that
# was then copied into the shiny app.R file. Here, I adjusted the "data" tibble
# as needed to create graphs that visualized changes in voter registration and
# changes in Hispanic populations in each county over time. This code is also
# present in the app.R file.

data %>% 
  filter(year == 2010 | year == 2018) %>% 
  filter(party == "democrat") %>% 
  select(county, year, hisp_pop) %>% 
  pivot_wider(names_from = year, values_from = hisp_pop, names_prefix = "pop_") %>% 
  group_by(county) %>% 
  summarize(perc_change_hisp = ((pop_2018 - pop_2010) / pop_2010) * 100) %>% 
  ggplot(aes(x = reorder(county, perc_change_hisp), y = perc_change_hisp)) +
    geom_col() +
    coord_flip()

hisp_pop_statewide <- data %>% 
  filter(year == 2010 | year == 2018) %>% 
  filter(party == "democrat") %>% 
  select(county, year, hisp_perc) %>% 
  pivot_wider(names_from = year, values_from = hisp_perc, names_prefix = "perc_") %>% 
  group_by(county) %>% 
  summarize(perc_change_hisp_perc = perc_2018 - perc_2010) %>% 
  ggplot(aes(x = reorder(county, perc_change_hisp_perc), y = perc_change_hisp_perc)) +
    geom_col(fill = "navyblue") +
    theme_classic() +
    labs(x = NULL,
         y = "Change in Hispanic Percentage of Population",
         title = "Hispanic Populations Have Grown Faster \n Than County Populations Overall",
         subtitle = "Betweeen 2010 and 2018") +
    coord_flip()

# Also before I knew how shiny worked, I figured it would be easier to paste
# non-dynamic plots in with a ggsave. I eventually realized this was not the
# case. As with the functions above, I leave this in as a bit of diary entry.

# It did end up being useful though, because I later wanted a graph that
# illustrated Hispanic population growth in AZ for another class.

ggsave("hisp_pop_statewide.png", plot = hisp_pop_statewide)
```

```{r relative_reg_gains_1, include = FALSE}

# Like above, this is my data adjusting chunk for a graph illustrating party
# registration gains by county relative to the other major party. This code is
# also in the shiny app.R file.

data %>%
  select(county, year, party, registration) %>% 
  pivot_wider(names_from = party, values_from = registration) %>% 
  mutate(difference = democrat - republican) %>% 
  select(county, year, difference) %>% 
  pivot_wider(names_from = year, values_from = difference, names_prefix = "diff_") %>% 
  mutate(diff_from_2010 = diff_2018 - diff_2010,
         diff_from_2012 = diff_2018 - diff_2012,
         diff_from_2014 = diff_2018 - diff_2014,
         diff_from_2016 = diff_2018 - diff_2016) %>%
  select(county, diff_from_2010, diff_from_2012, diff_from_2014, diff_from_2016) %>% 
  pivot_longer(diff_from_2010:diff_from_2016, names_to = "year", values_to = "difference",
               names_prefix = "diff_from_") %>% 
  filter(year == "2016") %>% 
  ggplot(aes(x = reorder(county, difference), y = difference, fill = difference < 0)) +
    geom_col(show.legend = FALSE) +
    theme_classic() +
    labs(x = NULL,
         y = "Registration Gains Relative to Other Party",
         title = "Where Has Each Party Improved?",
         subtitle = "Between 2012 and 2018") +
    coord_flip() +
    scale_fill_manual(values = c("blue3", "red2"))
``` 

```{r relative_reg_gains_2, echo = FALSE}

# An old version of how I was trying to create the graph above. Left as a diary
# entry!

data %>% 
    filter(year == 2012 | year == 2018) %>% 
    select(county, year, party, registration) %>% 
    pivot_wider(names_from = party, values_from = registration) %>% 
    mutate(difference = democrat - republican) %>% 
    select(county, year, difference) %>% 
    pivot_wider(names_from = year, values_from = difference, names_prefix = "diff_") %>% 
    mutate(diff_change = diff_2018 - diff_2012) %>%
    ggplot(aes(x = reorder(county, diff_change), y = diff_change, fill = diff_change < 0)) +
    geom_col(show.legend = FALSE) +
    theme_classic() +
    labs(x = NULL,
         y = "Registration Gains Relative to Other Party",
         title = "Where Has Each Party Improved?",
         subtitle = "Between 2012 and 2018") +
    coord_flip() +
    scale_fill_manual(values = c("blue", "red"))
```

```{r correlations_old, include = FALSE}

# Data adjusting to create a gt table that illustrated the effect of changes in
# a county's Hispanic population on the democratic party's vote share in that
# county.

# I later learned that this kind of data analysis was not quite what I was
# looking to do. This gt table is thus not included in the shiny app, and is
# replaced with the one created below in code chunk "correlations_new". However,
# like all of my other mistakes above, I am leaving it in for future reference!

perc_change_votes <- data %>% 
  filter(year == 2010 | year == 2018) %>% 
  filter(party == "democrat") %>% 
  select(county, year, percentage_votes) %>% 
  pivot_wider(names_from = "year", values_from = "percentage_votes", names_prefix = "votes_") %>% 
  mutate(perc_change_votes = votes_2018 - votes_2010) %>% 
  select(county, perc_change_votes)

data %>% 
  filter(year == 2010 | year == 2012) %>% 
  filter(party == "democrat") %>% 
  select(county, year, hisp_perc) %>% 
  pivot_wider(names_from = "year", values_from = "hisp_perc", names_prefix = "hisp_perc_") %>% 
  mutate(perc_change_hisp = hisp_perc_2012 - hisp_perc_2010) %>% 
  select(county, perc_change_hisp) %>% 
  full_join(perc_change_votes, by = "county") %>%
    gt() %>% 
      tab_header(title = "Effect on Change in Hispanic Population on Democratic Vote Share",
                 subtitle = "From 2010 to 2018") %>% 
      tab_spanner(label = "Correlation = -0.058", columns = TRUE) %>% 
      cols_align(align = "center", columns = TRUE) %>% 
      fmt_number(columns = vars(perc_change_votes), decimals = 2) %>% 
      cols_label(county = "County",
                 perc_change_hisp = "Change in Hispanic Share of Population (%)",
                 perc_change_votes = "Change in Democratic Vote Share (%)")
```

```{r map, echo=FALSE}

# Using the code from past in-class exercises and problem set 4 (I think) to
# create a demographic map of Arizona.

arizona <- get_acs(geography = "county",
                      state = "AZ",
                      variables = "DP05_0071PE",
                      year = 2018,
                      geometry = TRUE)

arizona %>% 
  ggplot(aes(fill = estimate)) +
  geom_sf() +
  theme_void() +
  scale_fill_viridis_c(direction = -1, option = "plasma") +
  labs(title = "Hispanic or Latinx Percent of Arizona Population",
       fill = "Percentage")
```

```{r map_data, echo=FALSE}

# Here, I am making data adjustments so that I can create a dynamic graph in
# which the user can drag their mouse over a county (sort of) and see the
# election results in that county for a given election year.

az_county_results <- data %>% 
  select(county, year, party, percentage_votes) %>% 
  pivot_wider(names_from = party, values_from = percentage_votes) %>% 
  mutate(difference = democrat - republican) %>% 
  mutate(county_full = paste(county, "County, Arizona")) %>% 
  select(county_full, year, democrat, republican, difference)

arizona_county_results_map <- arizona %>% 
  full_join(az_county_results, by = c("NAME" = "county_full")) %>% 
  mutate(democrat_rounded = round(democrat, digits = 2)) %>% 
  mutate(republican_rounded = round(republican, digits = 2))
```

```{r correlations_new, echo=FALSE}

# Here I realize and correct the statistical mistakes I made in the code chunk
# "correlations_old". By separating by county, you can see that there's a very
# strong correlation between demographic changes and electoral changes in each
# county. This correlation is not equally impactful in every county however!
# This was the issue in "correlations_old"--I was trying to correlate the impact
# of changes, not the changes themselves.

y <- data %>% 
  filter(party == "democrat") %>%
  group_by(year) %>% 
  summarize(total_hisp_pop = sum(hisp_pop), 
            total_pop = sum(total_pop),
            total_dem_votes = sum(candidatevotes),
            total_votes = sum(totalvotes)) %>% 
  mutate(hisp_perc_az = (total_hisp_pop / total_pop) * 100) %>% 
  mutate(dem_perc_az = (total_dem_votes / total_votes) * 100) %>% 
  mutate(county = "OVERALL") %>% 
  select(county, year, hisp_perc_az, dem_perc_az)

data %>% 
  filter(party == "democrat") %>% 
  full_join(y, by = c("county",
                      "year",
                      "hisp_perc" = "hisp_perc_az",
                      "percentage_votes" = "dem_perc_az")) %>% 
  group_by(county) %>% 
  mutate(correlation = cor(hisp_perc, percentage_votes)) %>% 
  filter(year == 2018) %>% 
  select(county, correlation) %>% 
  ungroup() %>%
  arrange(desc(correlation)) %>% 
  gt() %>% 
    tab_header(title = "Effect of Changes in Hispanic Population on Democratic Vote Share") %>% 
    tab_spanner(label = "From 2010 to 2018", columns = TRUE) %>% 
    cols_align(align = "center", columns = TRUE) %>% 
  cols_label(county = "County",
             correlation = "Correlation")
```

```{r model, echo=FALSE}

# Here I create a simple model for predicting democratic vote share in a given
# county based on hispanic population. It effectively shows that a 1% increase
# in Hispanic population will lead to a 2% increase in democratic vote share. To
# me, this seems like demographic chnages account for bout half of the change,
# but are predictive of the full change...if that makes sense. Pretty accurate!

model_1 <- lm(percentage_votes ~ hisp_perc + county,
             data = data_dems)

model_1 %>% 
  tidy(conf.int = TRUE) %>% 
  select(term, estimate, conf.low, conf.high) %>% 
  gt() %>% 
    tab_header(title = "Efffect of Hispanic Population Change on Democratic Vote Share") %>% 
    tab_spanner(label = "Default Estimate is Apache County", columns = TRUE) %>% 
    cols_label(term = "Variable",
               estimate = "Estimate",
               conf.low = "Lower Bound",
               conf.high = "Upper Bound") %>% 
    tab_footnote(footnote = "Data from U.S. Census Bureau and Arizona Secretary of State",
                 cells_title())

predict(model_1, newdata = tibble(hisp_perc = 6, county = "Apache")) %>% 
  gt() %>% 
    cols_label(value = "Dem %")
```

```{r hisp_pop_county}

# Here I create a last gt table that shows the Hispanic population in each
# county in 2018. This information is useful when interacting with the model
# above. The model isn't very useful if you don't know what an appropriate
# Hispanic population is for a given county, so this allows you to make somewhat
# useful predictions of democratic vote share based on some expected Hispanic
# population growth.

data %>% 
  filter(year == 2018) %>% 
  filter(party == "democrat") %>% 
  select(county, hisp_perc) %>% 
  arrange(desc(hisp_perc)) %>% 
  gt() %>% 
    tab_header(title = "Hispanic Populations by County") %>% 
    tab_spanner(label = "2018 American Community Survey", columns = TRUE) %>% 
    tab_footnote(footnote = "Data from U.S. Census Bureau", cells_title()) %>% 
    cols_label(county = "County",
               hisp_perc = "Percentage") %>% 
    cols_align(align = "center", columns = TRUE)
```
